name: Data Preprocessing Engine

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install pandas numpy qiskit qiskit-aer
        
      - name: List files
        run: ls -R
        
      - name: Run Full Quantum Pipeline
        run: |
          python src/data_preprocessor.py
          python src/data_ingestion.py
          python src/quantum_matrix_engine.py
          python src/decision_decoder.py
